version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: aqro_user
      POSTGRES_PASSWORD: strongpass
      POSTGRES_DB: aqro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://aqro_user:strongpass@db:5432/aqro_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
